apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
resources:
  - EFS-Provisioner.yml
  - Rbac.yml
  - storage.yml
  - mysql.yml
  - wordpress-deploy.yml